# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11c5556034343f6645a66b7eb0c9318a51913426186bd1d39eb8838664e02977a99027884edeeae6ac7693c8e4dcbf53c07341024577de9d707c53fde0d9d30a

test:
  secret_key_base: ccf7a8eb32a79cb7f4f7fd64df7d6095c21c2fc89ab80968cf260943ba9f763aacaeb7ee87ea8f397b5a56f3ad68e5c33d2e27020ae5eff541cd9d5a061c4a8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
